{
"detectSources":
   {"sigma":
       {"default":0.0,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       },
    "threshold":
       {"default":2.5,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       },
    "fwhm":
       {"default":5.5,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       }
   },

"addReferenceCatalogs":
   {"catalogName":
       {"default":None,
        "recipeOverride":True,
        "userOverride":True,
        "type":"str",
        "uiLevel":"UIBASIC"
       }
   },

"correlateWithReferenceCatalogs":
   {"delta":
       {"default":7.0,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       },
    "firstPass":
       {"default":50.0,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       },
   },
"calculateZeropoint":
   {"zplogfile":
       {"default":"ZPcorr.log",
        "recipeOverride":True,
        "userOverride":True,
        "type":"str",
        "uiLevel":"UIBASIC"
       },
    "extinction":
       {"default":None,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       }
   },
"fluxcal":
   {"addBPM":
       {"default":True,
        "recipeOverride":True,
        "userOverride":True,
        "type":"bool",
        "uiLevel":"UIBASIC"
       },
    "sigma":
       {"default":0.0,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       },
    "threshold":
       {"default":2.5,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       },
    "fwhm":
       {"default":5.5,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       },
    "delta":
       {"default":7.0,
        "recipeOverride":True,
        "userOverride":True,
        "type":"float",
        "uiLevel":"UIBASIC"
       }
   }
}
